### PR TITLE
enhancement/move error catching #20

### LINKED ISSUE #20: Move error catching from Service functions to Framework
### Description
Currently all Services have a try catch block in their `validateConfig()` and `createClient()` functions.
These should be pulled into the Framework to the functions which call these to reduce code completion and to prevent Services from being able to crash NodeCG if they don't handle exceptions or maybe forget.
Also this lowers the amount of work that is required to create a Service.

### PR DESCRIPTION
**Pull request by Tim-Tech-Dev**
should close #20

### CODE REVIEW

File: nodecg-io-core/extension/instanceManager.ts [hunk 1]
```diff
@@ -119,9 +119,15 @@ export class InstanceManager {
...
-                return error("Config invalid: " + validationRes.errorMessage);
+            try {
+                const validationRes = await service.result.validateConfig(config);
+                if (validationRes.failed) {
+                    return error("Config invalid: " + validationRes.errorMessage);
+                }
+            } catch (err) {
+                this.nodecg.log.error(
+                    `The "${inst.serviceType}" service function produced an error while config verefication: ${err}`,
+                );
```
Comment (daniel0611) [inline nodecg-io-core/extension/instanceManager.ts:130]: What was the reasoning to just log and don't return here? When the verification functions throws an error we currently just continue, set the config and create the client using a config that hasn't passed the validation function.
Also logging on the console in addition to the GUI is fine, but then we should stop and don't use the invalid config.

File: nodecg-io-core/extension/instanceManager.ts [hunk 2]
```diff
@@ -159,17 +165,23 @@ export class InstanceManager {
...
+                    inst.client = undefined;
+                } else {
+                    // Update service instance object
+                    inst.client = client.result;
+                }
+            } catch (err) {
                 this.nodecg.log.error(
-                    `The "${inst.serviceType}" service produced an error while creating a client: ${client.errorMessage}`,
+                    `The "${inst.serviceType}" service function produced an error while creating a client: ${err}`,
                 );
```
Comment (daniel0611) [inline nodecg-io-core/extension/instanceManager.ts:184]: Same as in the `updateInstanceConfig` method.
Also if the client fails to create we should unset the client same as in the if above if the service returns an error.

**Comment by Tim-Tech-Dev** [comment]
No double errors in the GUI if there is no try catch block in the service implementations.
They will be removed in #42

File: nodecg-io-core/extension/instanceManager.ts [hunk 3]
```diff
@@ -159,17 +163,26 @@ export class InstanceManager {
...
+            try {
+                const client = await service.result.createClient(inst.config);
+
+                // Check if a error happened while creating the client
+                if (client.failed) {
+                    this.nodecg.log.error(
+                        `The "${inst.serviceType}" service produced an error while creating a client: ${client.errorMessage}`,
+                    );
+                    inst.client = undefined;
+                    return;
```
Comment (daniel0611) [inline nodecg-io-core/extension/instanceManager.ts:175]: We shouldn't return here and unset the client.
In case a client fails to be created the bundles should get undefined as the user did want to change the credentials and the bundles should use old ones.
```suggestion
```

File: nodecg-io-core/extension/instanceManager.ts [hunk 4]
```diff
@@ -159,17 +163,26 @@ export class InstanceManager {
...
+            } catch (err) {
                 this.nodecg.log.error(
-                    `The "${inst.serviceType}" service produced an error while creating a client: ${client.errorMessage}`,
+                    `The "${inst.serviceType}" service function produced an error while creating a client: ${err}`,
                 );
                 inst.client = undefined;
-            } else {
-                // Update service instance object
-                inst.client = client.result;
+                return;
```
Comment (daniel0611) [inline nodecg-io-core/extension/instanceManager.ts:185]:
```suggestion
```
